
name: Gerar EXE do Loja do Zero

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependencias
        run: pip install pygame pyinstaller

      - name: Criar EXE
        run: pyinstaller --onefile --windowed --name LojaDoZero main.py

      - name: Enviar EXE
        uses: actions/upload-artifact@v4
        with:
          name: LojaDoZero-Windows
          path: dist/LojaDoZero.exe

